Onboard UI Update
ComputerScienceHouse/Devcade-onboard pull request #5
Opened 2022-11-09 01:39 UTC by Nate-Teall

Most of what is changed is in Game1.cs, Menu.cs, and MenuCard.cs. Mostly visual changes like animated background and loading screens. The backend stuff with getting games/assets from the server is unchanged and will need to be fixed still.

2022-11-09 05:35 UTC, MTFT-Games commented
suggestion: use sprite maps instead of 70 individual frames

2022-11-10 00:29 UTC, Nate-Teall commented
> suggestion: use sprite maps instead of 70 individual frames

Alright, I will do that next

2022-11-10 21:08 UTC, WillNilges commented
```/Devcade-onboard/onboard/Content/devcade-menu-big.spritefont : error : Processor 'FontDescriptionProcessor' had unexpected failure! [/Devcade-onboard/onboard/onboard.csproj]
/Devcade-onboard/onboard/Content/devcade-menu-title.spritefont : error : Processor 'FontDescriptionProcessor' had unexpected failure! [/Devcade-onboard/onboard/onboard.csproj]
/root/.nuget/packages/monogame.content.builder.task/3.8.0.1641/build/MonoGame.Content.Builder.Task.targets(138,5): error MSB3073: The command "dotnet /root/.nuget/packages/monogame.content.builder.task/3.8.0.1641/build//../tools/netcoreapp3.1/any/mgcb.dll /quiet /@:"/Devcade-onboard/onboard/Content/Content.mgcb" /platform:DesktopGL /outputDir:"/Devcade-onboard/onboard/Content/bin/DesktopGL/Content" /intermediateDir:"/Devcade-onboard/onboard/Content/obj/DesktopGL/Content" /workingDir:"/Devcade-onboard/onboard/Content/"" exited with code 2. [/Devcade-onboard/onboard/onboard.csproj]

The build failed. Fix the build errors and run again.```

2022-11-10 22:58 UTC, WillNilges requested changes

2022-11-10 22:58 UTC, WillNilges commented on onboard/Content/devcade-menu-big.spritefont
> +    /usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf
Delete this comment?

2022-11-10 22:59 UTC, WillNilges approved these changes
:shipit:

2022-11-10 23:00 UTC, merged