Rust Backend Rewrite
ComputerScienceHouse/Devcade-onboard pull request #50
Opened 2023-04-02 21:59 UTC by joeoneil

Rewrote the backend in Rust to allow for more stability in the API interface and allow expansion of the backend to communicate with games for saving / loading, as well as gatekeeper integration down the line.

2023-04-06 02:35 UTC, MTFT-Games approved these changes
Im tired and dont know rust but if its tested and runs it looks vaguely alright to me conceptually.

2023-04-06 02:35 UTC, MTFT-Games commented on onboard/backend/src/lib.rs
> +// TODO Update struct to match new schema
Does this not need to be done prior to merge?

2023-04-06 16:54 UTC, WillNilges commented
Is there documentation (compilation/installation guide, environment variable sample file, etc)?

2023-04-06 17:19 UTC, WillNilges commented
Got it running for a little bit. I had to use the `.env.template` inside the `onboard/` directory and fill it out. It needed some log file paths, resolution, and a directory, presumably to store game data in. Now it's crashing with cryptic messages
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x340
  Serial number of failed request:  389
  Current serial number in output stream:  390
```

2023-04-06 18:53 UTC, joeoneil commented on onboard/backend/src/lib.rs
> +// TODO Update struct to match new schema
Forgot to remove this. The definition for devcade game currently lives in api/schema.rs, and is updated to the new format.

2023-04-06 23:15 UTC, MTFT-Games requested changes
Actually, imma make you update the readme first

2023-04-07 00:11 UTC, MTFT-Games requested changes
specific readme updates

2023-04-07 00:11 UTC, MTFT-Games commented on README.md
> +To build and run on the Idiot, do the following from `./onboard/frontend`:
We are moving away from using the 'idiot' terminology. Use DCU (devcade compute unit) instead

2023-04-07 00:11 UTC, MTFT-Games commented on README.md
> +To put it on the Idiot, compress the `publish` folder located at `./onboard/frontend/bin/Release/netcoreapp3.1/linux-x64` and `scp` that to the Idiot.
We are moving away from using the 'idiot' terminology. Use DCU (devcade compute unit) instead

2023-04-07 00:11 UTC, MTFT-Games commented on README.md
> +You'll also want to `scp` `./onboard/backend/target/release` to the Idiot.
We are moving away from using the 'idiot' terminology. Use DCU (devcade compute unit) instead

2023-04-07 00:11 UTC, MTFT-Games commented on onboard/.env.template
> +# This file should be copies to .env and filled with the correct values
This should be added to readme .env section

2023-04-15 00:00 UTC, closed without merging